version: '3.8'

volumes:
  postgres_data:
  staticfiles:

services:
  db:
    image: postgres:12.4
    environment:
      - POSTGRES_PASSWORD=postgrespass
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  web:
    image: ipsiman/yamdb:v0.1
    volumes:
      - staticfiles:/code/static
    depends_on:
      - db

  nginx:
    image: nginx:1.19.6
    volumes:
      - staticfiles:/static
      - ./host.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8000:80
    depends_on:
      - web
